language: R
sudo: false
cache: packages

r_packages:
  - bookdown

before_script:
  - make gitbook

deploy:
  provider: pages                      # Specify the gh-pages deployment method
  skip_cleanup: true                   # Don't remove files
  github_token: $GITHUB_TOKEN          # Set in travis-ci.org dashboard
  local_dir: docs                      # Deploy the docs folder
  on:
    branch: master

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH

notifications:
  email: false
